language: python

python:
  - "3.9"
  - "3.10"

install:
  - pip install pytest pytest-cov ruff build

script:
  - make lint
  - make test
  - make coverage

after_script:
  - make fortifications || true
