language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

install:
#  - pip install .
#  - pip install -r requirements.txt

# command to run tests
script: pwd;python -m pytest

after_script: cd qtop/contrib/ ;./func_tests.sh
