[build-system]
requires = [
    "setuptools>=44,<60; python_version < '3.7'",
    "setuptools>=61.0; python_version >= '3.7'",
]
build-backend = "setuptools.build_meta"

[project]
name = "qtop"
dynamic = ["version"]
description = """
    qtop: the fast text mode way to monitor your cluster's utilization and status;
    the time has come to take back control of your cluster's scheduling business"""
readme = "README.rst"
authors = [
    { name="Sotiris Fragkiskos", email="sfranky@gmail.com"},
    { name="Fotis Georgatos", email="kefalonia@gmail.com"},
]
requires-python = ">=3"

[project.urls]
"Homepage" = "https://github.com/qtop/qtop"

[project.scripts]
qtop = "qtop_py.qtop:main"

[tool.setuptools.dynamic]
version = {attr = "qtop_py.__version__"}

[tool.setuptools]
packages = ["qtop_py"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["I001"]

target-version = "py36"

line-length = 188

[tool.ruff.lint.per-file-ignores]
"qtop_py/qtop.py" = ["F405"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::SyntaxWarning",
]
