[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qtop"
dynamic = ["version"]
description = "qtop: the fast text mode way to monitor your cluster's utilization and status"
readme = "README.md"
authors = [
    { name="Sotiris Fragkiskos", email="sfranky@gmail.com"},
    { name="Fotis Georgatos", email="kefalonia@gmail.com"},
]
requires-python = ">=3"

[project.urls]
"Homepage" = "https://github.com/qtop/qtop"

[project.scripts]
qtop = "qtop_py.qtop:main"

[tool.setuptools.dynamic]
version = {attr = "qtop_py.__version__"}

[tool.setuptools]
include-package-data = false
packages = ["qtop_py", "qtop_py.plugins", "qtop_py.ui"]

[tool.setuptools.package-data]
qtop_py = ["contrib/*", "inputs/*", "web/*"]

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
lint.select = ["E", "F", "I"] ##
lint.ignore = ["E722"]

# Assuming you're developing for Python 3.10
target-version = "py310" ##

## FG customisations
line-length = 188 # this is temporary to reduce noise over line lengths

[tool.ruff.lint.per-file-ignores]
"qtop_py/qtop.py" = ["F401", "F403", "F405", "F522", "F841"]
