[build-system]
requires = [
    "setuptools>=44,<60; python_version < '3.7'",
    "setuptools>=61.0; python_version >= '3.7'",
]
build-backend = "setuptools.build_meta"

[project]
name = "qtop"
dynamic = ["version"]
description = "qtop: the fast text mode way to monitor your cluster's utilization and status"
readme = "README.md"
authors = [
    { name="Sotiris Fragkiskos", email="sfranky@gmail.com"},
    { name="Fotis Georgatos", email="kefalonia@gmail.com"},
]
requires-python = ">=3.6"

[project.urls]
"Homepage" = "https://github.com/qtop/qtop"

[project.scripts]
qtop = "qtop_py.qtop:main"

[tool.setuptools.dynamic]
version = {attr = "qtop_py.__version__"}

[tool.setuptools]
packages = ["qtop_py"]

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
lint.select = ["E", "F", "I"] ##
lint.ignore = ["E722"]

# Keep lint suggestions compatible with the oldest supported runtime.
target-version = "py36" ##

## FG customisations
line-length = 188 # this is temporary to reduce noise over line lengths
