[metadata]
name = qtop
version = attr: qtop_py.__version__
description = qtop: the fast text mode way to monitor your cluster's utilization and status; the time has come to take back control of your cluster's scheduling business
long_description = file: README.md
long_description_content_type = text/markdown
author = Sotiris Fragkiskos, Fotis Georgatos
author_email = sfranky@gmail.com, kefalonia@gmail.com
url = https://github.com/qtop/qtop

[options]
packages = find:
include_package_data = False
python_requires = >=3

[options.packages.find]
include = qtop_py*
namespaces = False

[options.package_data]
qtop_py =
    contrib/*
    inputs/*
    web/*

[options.entry_points]
console_scripts =
    qtop = qtop_py.qtop:main
