name: build-qtop

on:
  push:
    branches:
      - main
      - develop
      - 'releases/**'
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.10'
      - run: pip install build twine
      - run: pyproject-build
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: qtop-dist
          path: dist/
